version: 0.0
os: linux
files:
  - source: backend/target/backend-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
