version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - echo Installing backend...
      - cd backend
      - mvn clean install -DskipTests
      - cd ../frontend
      - echo Installing frontend...
      - npm install

  build:
    commands:
      - echo Building frontend...
      - npm run build
      - cd ..
      - echo Copying frontend to backend static folder...
      - cp -r frontend/build/* backend/src/main/resources/static/
      - cd backend
      - echo Building JAR...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Deploying via SSM...
      - aws ssm send-command \
          --instance-ids i-0de2d6bb45d4b7a19 \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy app" \
          --parameters 'commands=["pkill -f java || true", "java -jar /home/ec2-user/app.jar > /home/ec2-user/app.log 2>&1 &"]' \
          --region us-east-1

artifacts:
  files:
    - backend/target/*.jar
