version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
    commands:
      - echo Installing frontend and backend dependencies
      - cd frontend
      - npm install
      - cd ../backend
      - ./mvnw clean install -DskipTests
      - cd ..

  build:
    commands:
      - echo Building frontend
      - cd frontend
      - npm run build
      - cd ..
      - echo Frontend built

      - echo Building backend
      - cd backend
      - ./mvnw package -DskipTests
      - cd ..
      - echo Backend built

  post_build:
    commands:
      - echo Preparing deployment
      - mkdir -p deploy
      - cp backend/target/*.jar deploy/backend.jar
      - cp -r frontend/build deploy/frontend

      # Fetching the private key from Secrets Manager
      - echo Fetching private key from Secrets Manager
      - aws secretsmanager get-secret-value --secret-id CodeBuild-EC2-SSH-KEY --query SecretString --output text > /tmp/private_key.pem
      - chmod 400 /tmp/private_key.pem

      # SSH into EC2 and deploy
      - echo Deploying to EC2
      - scp -o StrictHostKeyChecking=no -i /tmp/private_key.pem -r deploy/* ec2-user@52.87.178.31:/home/ec2-user/deploy
      - ssh -o StrictHostKeyChecking=no -i /tmp/private_key.pem ec2-user@52.87.178.31 << 'EOF'
          pkill -f 'backend.jar' || true
          nohup java -jar /home/ec2-user/deploy/backend.jar > /home/ec2-user/backend.log 2>&1 &
          sudo rm -rf /var/www/html/*
          sudo cp -r /home/ec2-user/deploy/frontend/* /var/www/html/
        EOF


artifacts:
  files:
    - deploy/**
