version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto17
    commands:
      - echo Installing dependencies...
      - cd frontend && npm install && cd ..
      - cd backend && mvn install -DskipTests && cd ..
      - echo Base64-encoding deployment package...
      - mkdir -p deploy
      - cp -r docker-compose.yml postScript.sh frontend backend deploy/
      - cd deploy && zip -r ../deploy.zip . && cd ..
      - base64 deploy.zip > deploy.b64
      - chmod 400 deploy.b64  # Make sure it's secure while building

  build:
    commands:
      - echo Building React app...
      - cd frontend && npm run build && cd ..
      - echo Packaging Spring Boot app...
      - cd backend && mvn package -DskipTests && cd ..
      - echo Preparing Docker deployment...

  post_build:
    commands:
      - echo Sending base64 payload to EC2 via SSM...
      - |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceIds,Values=i-07af2f3a6f8912fe1" \
          --comment "Deploy app via base64 payload" \
          --parameters '{
            "commands": [
              "cd /home/ec2-user",
              "echo $(cat deploy.b64) | base64 -d > deploy.zip",
              "unzip -o deploy.zip -d deploy",
              "chmod +x deploy/postScript.sh",
              "bash deploy/postScript.sh"
            ]
          }' \
          --region us-east-1

artifacts:
  files:
    - backend/target/*.jar
    - deploy/**/*
