version: 0.2

phases:
  install:
    commands:
      - echo Nothing to install

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REACT_REPO_URI=123456789012.dkr.ecr.us-east-1.amazonaws.com/react-app-repo
      - BACKEND_REPO_URI=123456789012.dkr.ecr.us-east-1.amazonaws.com/springboot-backend-repo
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REACT_REPO_URI
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $BACKEND_REPO_URI

  build:
    commands:
      - echo Building Docker images...
      - cd frontend
      - docker build -t react-app .
      - docker tag react-app:latest $REACT_REPO_URI:latest
      - cd ../backend
      - docker build -t springboot-backend .
      - docker tag springboot-backend:latest $BACKEND_REPO_URI:latest

  post_build:
    commands:
      - echo Pushing images to ECR...
      - docker push $REACT_REPO_URI:latest
      - docker push $BACKEND_REPO_URI:latest

artifacts:
  files: []
