version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto11
    commands:
      - echo "Checking directory structure..."
      - ls -la
      - echo "Installing frontend dependencies..."
      - cd frontend
      - ls -la
      - npm install
      - cd ..
      - echo "Installing backend dependencies..."
      - cd backend
      - ls -la
      - mvn install -DskipTests
      - cd ..
      - echo "Installing AWS CLI..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - echo "Fetching EC2 private key from SSM Parameter Store..."
      - aws ssm get-parameter --name /ec2/key-pair --with-decryption --query 'Parameter.Value' --output text > ec2-key.pem
      - chmod 400 ec2-key.pem
      - echo "Key fetched successfully!"

  build:
    commands:
      - echo "Building React frontend..."
      - cd frontend
      - npm run build
      - cd ..
      
      - echo "Copying frontend build to Spring Boot static folder..."
      - cp -r frontend/build/* backend/src/main/resources/static/

      - echo "Building backend JAR..."
      - cd backend
      - mvn package -DskipTests
      - cd ..

      - echo "Copying backend JAR to deploy directory..."
      - mkdir -p deploy
      - ls -al backend/target/
      - cp backend/target/*.jar deploy/
      - cp postScript.sh deploy/

  post_build:
    commands:
      - echo "Sending files to EC2..."
      - scp -o StrictHostKeyChecking=no -i ec2-key.pem -r deploy/ ec2-user@34.229.200.248:/home/ec2-user/

artifacts:
  files:
    - backend/target/*.jar
    - deploy/**/*
  discard-paths: no
