version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto11
    commands:
      - cd frontend && npm install && cd ..
      - cd backend && mvn install -DskipTests && cd ..
      - aws secretsmanager get-secret-value --secret-id abc --query SecretString --output text > ec2-key.pem
      - chmod 400 ec2-key.pem

  build:
    commands:
      - cd frontend && npm run build && cd ..
      - cp -r frontend/build/* backend/src/main/resources/static/
      - cd backend && mvn package -DskipTests && cd ..
      - mkdir -p deploy && cp backend/target/*.jar deploy/
      - cp postScript.sh deploy/

  post_build:
    commands:
      - scp -o StrictHostKeyChecking=no -i ec2-key.pem -r deploy/ ec2-user@34.229.200.248:/home/ec2-user/
      - aws ssm send-command --document-name "AWS-RunShellScript" --targets "Key=instanceIds,Values=i-07af2f3a6f8912fe1" --parameters '{"commands":["/home/ec2-user/start-app.sh"]}' --region us-east-1

artifacts:
  files:
    - backend/target/*.jar
    - deploy/**/*
