version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto11
    commands:
      - echo Installing frontend dependencies...
      - cd frontend
      - npm install
      - cd ..
      - echo Installing backend dependencies...
      - cd backend
      - mvn install
  build:
    commands:
      - echo Building React frontend...
      - cd ../frontend
      - npm run build
      - echo Copying frontend build to Spring Boot static folder...
      - cp -r build/* ../backend/src/main/resources/static/
      - echo Building backend JAR...
      - cd ../backend
      - mvn package -DskipTests
      - cp postScript.sh deploy/  # <-- explicitly copy to deploy folder
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    #- '**/*'  
    - deploy/**/*        
    - backend/target/*.jar      # This includes postScript.sh and everything else
  discard-paths: no
