version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto17
    commands:
      - echo Installing dependencies...
      - cd frontend && npm install && cd ..
      - cd backend && mvn install -DskipTests && cd ..
      - aws secretsmanager get-secret-value --secret-id /ec2/key-pair --query SecretString --output text > ec2-key.pem
      - chmod 400 ec2-key.pem

  build:
    commands:
      - echo Building React app...
      - cd frontend && npm run build && cd ..
      - echo Packaging Spring Boot app...
      - cd backend && mvn package -DskipTests && cd ..
      - echo Preparing Docker deployment...
      - mkdir -p deploy
      - cp -r docker-compose.yml postScript.sh frontend backend deploy/

  post_build:
    commands:
      - echo Deploying to EC2 via SCP...
      - scp -o StrictHostKeyChecking=no -i ec2-key.pem -r deploy/ ec2-user@34.229.200.248:/home/ec2-user/
      - echo Starting containers on EC2...
      - aws ssm send-command --document-name "AWS-RunShellScript" --targets "Key=instanceIds,Values=i-07af2f3a6f8912fe1" --parameters '{"commands":["/home/ec2-user/deploy/postScript.sh"]}' --region us-east-1

artifacts:
  files:
    - backend/target/*.jar
    - deploy/**
