version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
    commands:
      - echo Installing frontend and backend dependencies
      - cd frontend
      - npm install
      - cd ../backend
      - ls -l  # List files in backend folder to ensure mvnw is present
      - chmod +x ./mvnw  # Make sure mvnw is executable
      - ./mvnw clean install -DskipTests  # Run mvnw to build the backend
      - cd ..

  build:
    commands:
      - echo Building frontend
      - cd frontend
      - npm run build
      - cd ..
      - echo Frontend built

      - echo Building backend
      - cd backend
      - ./mvnw package -DskipTests
      - cd ..
      - echo Backend built

  post_build:
    commands:
      - echo Preparing deployment
      - mkdir -p deploy
      - cp backend/target/*.jar deploy/backend.jar
      - cp -r frontend/build deploy/frontend

      # Fetching the private key from Secrets Manager
      - echo Fetching private key from Secrets Manager
      - aws secretsmanager get-secret-value --secret-id CodeBuild-EC2-SSH-KEY --query SecretString --outpu
