version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto11
    commands:
      - echo "Checking directory structure..."
      - ls -la
      - echo "Installing frontend dependencies..."
      - cd frontend
      - npm install
      - cd ..
      - echo "Installing backend dependencies..."
      - cd backend
      - mvn install -DskipTests
      - cd ..
      - echo "Fetching EC2 private key from SSM Parameter Store..."
      - aws ssm get-parameter --name /ec2/key-pair --with-decryption --query 'Parameter.Value' --output text > ec2-key.pem
      - chmod 400 ec2-key.pem
      - echo "Key fetched successfully!"

  build:
    commands:
      - echo "Building React frontend..."
      - cd frontend
      - npm run build
      - cd ..
      
      - echo "Copying frontend build separately to deploy folder (optional for Apache)..."
      - mkdir -p deploy/frontend
      - cp -r frontend/build deploy/frontend/

      - echo "Copying frontend to Spring Boot static resources..."
      - cp -r frontend/build/* backend/src/main/resources/static/

      - echo "Building backend JAR..."
      - cd backend
      - mvn package -DskipTests
      - cd ..

      - echo "Copying backend JAR and post-deploy script..."
      - mkdir -p deploy
      - cp backend/target/*.jar deploy/
      - cp postScript.sh deploy/

  post_build:
    commands:
      - echo "Sending deploy folder to EC2..."
      - scp -o StrictHostKeyChecking=no -i ec2-key.pem -r deploy/ ec2-user@34.229.200.248:/home/ec2-user/
      - echo "Triggering EC2 to start Spring Boot app"
      - aws ssm send-command --document-name "AWS-RunShellScript" --targets "Key=instanceIds,Values=i-07af2f3a6f8912fe1" --parameters '{"commands":["/home/ec2-user/start-app.sh"]}' --comment "Start Spring Boot app via CodeBuild" --region us-east-1

            
artifacts:
  files:
    - backend/target/*.jar
    - deploy/**/*
  discard-paths: no
