version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - echo Installing backend...
      - cd backend
      - mvn clean install -DskipTests
      - cd ../frontend
      - echo Installing frontend...
      - npm install

  build:
    commands:
      - echo Building frontend...
      - npm run build
      - cd ..
      - echo Copying frontend to backend static folder...
      - cp -r frontend/build/* backend/src/main/resources/static/
      - cd backend
      - echo Building JAR...
      - mvn package -DskipTests

  post_build:
    commands:
    - echo Downloading EC2 key from S3...
    - aws s3 cp s3://my-deployment-secrets/ec2-key.pem ec2-key.pem
    - chmod 400 ec2-key.pem
    - echo Deploying JAR to EC2...
    - scp -o StrictHostKeyChecking=no -i ec2-key.pem backend/target/*.jar ec2-user@<EC2_PUBLIC_IP>:/home/ec2-user/app.jar
    - ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@<EC2_PUBLIC_IP> "pkill -f 'java -jar' || true && nohup java -jar /home/ec2-user/app.jar > /home/ec2-user/app.log 2>&1 &"

artifacts:
  files:
    - backend/target/*.jar
