version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - echo Installing Maven and Node modules
      - cd frontend && npm install && cd ..
      - cd backend && mvn clean install -DskipTests && cd ..
  build:
    commands:
      - echo Building frontend...
      - cd frontend && npm run build && cd ..
  post_build:
    commands:
      - echo Copying frontend to Apache root
      - sudo rm -rf /var/www/html/*
      - sudo cp -r frontend/build/* /var/www/html/
      - echo Deploying backend...
      - sudo pkill -f 'backend-0.0.1-SNAPSHOT.jar' || true
      - nohup java -jar backend/target/backend-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
artifacts:
  files:
    - '**/*'
    - '!**/node_modules/**/*'
