version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto11
    commands:
      - echo "Installing frontend dependencies..."
      - cd frontend
      - npm install
      - cd ..
      - echo "Installing backend dependencies..."
      - cd backend
      - mvn install
      - cd ..
  build:
    commands:
      - echo "Building React frontend..."
      - cd frontend
      - npm run build
      - cd ..
      
      - echo "Copying frontend build to Spring Boot static folder..."
      - cp -r frontend/build/* backend/src/main/resources/static/

      - echo "Building backend JAR..."
      - cd backend
      - mvn package -DskipTests
      - cd ..

      - echo "Copying postScript.sh to deploy directory..."
      - mkdir -p deploy
      - cp postScript.sh deploy/
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - backend/target/*.jar
    - deploy/**/*       # Includes postScript.sh from deploy directory
  discard-paths: no
