version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=us-east-1
      - REPO_FRONTEND=my-frontend-app
      - REPO_BACKEND=my-backend-app
      - FRONTEND_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_FRONTEND
      - BACKEND_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_BACKEND
      - echo FRONTEND_URI=$FRONTEND_URI
      - echo BACKEND_URI=$BACKEND_URI
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Build React frontend Docker image...
      - cd frontend
      - docker build -t $FRONTEND_URI .
      - cd ..
      
      - echo Build Spring Boot backend Docker image...
      - cd backend
      - mvn package -DskipTests
      - docker build -t $BACKEND_URI .
      - cd ..

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $FRONTEND_URI
      - docker push $BACKEND_URI

      - echo Fetching SSH private key from Secrets Manager...
      - export PRIVATE_KEY=$(aws secretsmanager get-secret-value --secret-id abc --query SecretString --output text | jq -r '.["ssh-key"]')

      - echo Connecting to EC2 and deploying...
      - |
        ssh -o StrictHostKeyChecking=no -i <(echo "$PRIVATE_KEY") ec2-user@34.229.200.248 << 'EOF'
          REGION=us-east-1
          ACCOUNT_ID=309071121886
          FRONTEND_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/my-frontend-app
          BACKEND_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/my-backend-app

          echo Logging in to ECR...
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

          echo Pulling images...
          docker pull $FRONTEND_URI
          docker pull $BACKEND_URI

          echo Stopping old containers...
          docker stop frontend || true && docker rm frontend || true
          docker stop backend || true && docker rm backend || true

          echo Running new containers...
          docker run -d --name frontend -p 80:80 $FRONTEND_URI
          docker run -d --name backend -p 8080:8080 $BACKEND_URI
        EOF
