version: '3'

services:
  frontend:
    image: 309071121886.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    container_name: frontend
    ports:
      - "80:80"  # Expose frontend on port 80
    networks:
      - app-network

  backend:
    image: 309071121886.dkr.ecr.us-east-1.amazonaws.com/backend:latest
    container_name: backend
    ports:
      - "8080:8080"  # Expose backend on port 8080
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  # Nginx will serve both frontend and backend on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx config file
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
